DROP TABLE IF EXISTS Airlines;
DROP TABLE IF EXISTS Airports;
DROP TABLE IF EXISTS Flights;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Bookings;
DROP TABLE IF EXISTS Passengers;
DROP TABLE IF EXISTS Payments;