// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: airline.sql

package db

import (
	"context"
	"database/sql"
)

const createAirline = `-- name: CreateAirline :one
INSERT INTO Airlines (
  name,
  iata_code,
  icao_code
) VALUES (
  $1, $2, $3
) RETURNING id, name, iata_code, icao_code
`

type CreateAirlineParams struct {
	Name     string         `json:"name"`
	IataCode sql.NullString `json:"iata_code"`
	IcaoCode sql.NullString `json:"icao_code"`
}

func (q *Queries) CreateAirline(ctx context.Context, arg CreateAirlineParams) (Airline, error) {
	row := q.db.QueryRowContext(ctx, createAirline, arg.Name, arg.IataCode, arg.IcaoCode)
	var i Airline
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IataCode,
		&i.IcaoCode,
	)
	return i, err
}
